// src/components/education/education.tsx
import { useTranslation } from "react-i18next";
import concordia from "../../assets/concordia.png";
import cem from "../../assets/cem_v_2.jpg";

import styles from "./education.module.css";

export function Education() {
  const { t } = useTranslation();

  return (
    <div className={styles.card}>
      <div id="education" className="hiddenId"></div>
      <h3>{t("SECTIONS.EDUCATION")}</h3>
      <div className={styles.flexRow}>
        <img className={styles.educationImg} src={concordia} />
        <div className={styles.description}>
          <h4 className={styles.school}>{t("EDUCATION.CONCORDIA.SCHOOL")}</h4>
          <p className={styles.descriptionText}>
            {t("EDUCATION.CONCORDIA.DESC")}
          </p>
          <h5 className={styles.honor}>{t("EDUCATION.CONCORDIA.HONOR")}</h5>
          <div
            className={styles.honors}
            dangerouslySetInnerHTML={{
              __html: t("EDUCATION.CONCORDIA.HONORS"),
            }}
          ></div>
        </div>
      </div>

      <div className={styles.flexRow}>
        <img className={styles.educationImg} src={cem} />
        <div className={styles.description}>
          <h4 className={styles.school}>{t("EDUCATION.CEM.SCHOOL")}</h4>
          <p className={styles.descriptionText}>{t("EDUCATION.CEM.DESC")}</p>
        </div>
      </div>
    </div>
  );
}

// src/app/education/education.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-education',
  templateUrl: './education.component.html',
  styleUrls: ['./education.component.css']
})
export class EducationComponent {

}

<div id="education" class="card">
  <div class="card-block">
    <h3 class="anchor-offset">Education</h3>
    <div class="flex-row">
      <img class="education-img" src="assets/concordia.png" />
      <div class="description">
        <h4>{{ 'EDUCATION.CONCORDIA.SCHOOL' | translate }}</h4>
        <p>{{ 'EDUCATION.CONCORDIA.DESC' | translate }}</p>
        <h5>{{ 'EDUCATION.CONCORDIA.HONOR' | translate }}</h5>
        <div [innerHTML]="'EDUCATION.CONCORDIA.HONORS' | translate"></div>
      </div>
    </div>

    <div class="flex-row">
      <img class="education-img" src="assets/cem_v_2.jpg" />
      <div class="description">
        <h4>{{ 'EDUCATION.CEM.SCHOOL' | translate }}</h4>
        <p>{{ 'EDUCATION.CEM.DESC' | translate }}</p>
      </div>
    </div>
  </div>
</div>
