// src/components/footer/footer.tsx
import { useEffect, useState } from "react";
import { useApi } from "../../utilities/apiService";
import styles from "./footer.module.css";
import classNames from "classnames";
import { useLinks } from "../../utilities/linkService";

export function Footer() {
  const api = useApi();
  const [latestSha, setLatestSha] =
    useState<Awaited<ReturnType<typeof api.getLatestCommit>>>(null);
  const links = useLinks();

  useEffect(() => {
    api.getLatestCommit().then((sha) => {
      setLatestSha(sha);
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles.footer}>
      <div className={styles.footerRow}>
        <p>
          Made with
          <i
            className={classNames({
              fa: true,
              "fa-heart": true,
              [styles.heart]: true,
            })}
          ></i>
          in Montréal
        </p>
        <p className={classNames([styles.iconRow, styles.latestSha])}>
          <a target="__blank" href={latestSha?.link}>
            <i className="fa fa-github"></i>
            <span className={styles.sha}>{latestSha?.sha}</span>
          </a>
        </p>
        <p className={styles.iconRow}>
          {links.socialLinks.map((link, index) => {
            return (
              <a
                key={link.display}
                className={classNames([styles.aboutLink, styles.anchor])}
                target="__blank"
                href={link.href}
              >
                <span className={styles.linkDisplay}>{link.display}</span>
                {index !== links.socialLinks.length - 1 && (
                  <span className={styles.linkSeparator}>|</span>
                )}
                <i className={classNames([styles.linkIcon, link.icon])}></i>
              </a>
            );
          })}
        </p>
      </div>
    </div>
  );
}

// src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Link } from '../../models/link';
import { LinkService } from '../../services/link.service';
import { BehaviorSubject } from 'rxjs/internal/BehaviorSubject';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  public links: Link[] = [];

  constructor(private linkService: LinkService, public apiService: ApiService) { }

  public ngOnInit() {
    this.apiService.getLatestCommit();
    this.links = this.linkService.socialLinks;
  }
}

<div class="footer">
  <p>Made with
    <i class="fa fa-heart"></i> in Montréal</p>
  <p class="icon-row latest-sha">
    <a target="__blank" href="{{(apiService.latestSha | async)?.link}}">
      <i class="fa fa-github"></i>
      <span class="sha">{{(apiService.latestSha | async)?.sha}}</span>
    </a>
  </p>
  <p class="icon-row">
    <a target="__blank" *ngFor="let link of links" href="{{link.href}}">
      <i [ngClass]="link.icon"></i>
    </a>
  </p>
</div>
