// src/app/layout/layout.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Link } from '../../models/link';
import { LinkService } from '../../services/link.service';
import { TranslateService } from '@ngx-translate/core';
import { Analytics } from '../../services/analytics';

@Component({
  selector: 'app-layout',
  templateUrl: './layout.component.html',
  styleUrls: ['./layout.component.css']
})
export class LayoutComponent implements OnInit {

  @Output() onLanguageToggle: EventEmitter<void>; // eslint-disable-line @angular-eslint/no-output-on-prefix

  public links: Link[] = [];

  constructor(private linkService: LinkService, public translate: TranslateService) {
    this.onLanguageToggle = new EventEmitter<void>();
  }

  public ngOnInit() {
    this.links = this.linkService.sectionLinks;
  }

  public navigateTo(event: MouseEvent) {
    const anchorElement = this.findAnchor(event.target as HTMLElement) as HTMLAnchorElement;
    if (anchorElement) {
      document.querySelector(anchorElement.hash).scrollIntoView({
        behavior: 'smooth',
        block: 'start'
      });

      history.pushState(null, anchorElement.href, anchorElement.href);
      Analytics.sendEvent('event', 'Navigate', anchorElement.hash);
    }
  }

  public findAnchor(target: HTMLElement) {
    while (target && target.tagName !== 'A') {
      target = target.parentElement;
    }
    return target;
  }

  public changeLanguage() {
    this.onLanguageToggle.emit();
  }
}

<clr-main-container>
  <clr-header>
    <div class="branding">
      <a class="nav-link" href="#about">
        <img id="header-logo" src="assets/header_logo.png" />
      </a>
    </div>
    <div class="header-nav" [clr-nav-level]="1">
      <a *ngFor="let link of links" href="{{link.href}}" class="nav-link nav-text">{{ ('SECTIONS.' + link.display.toUpperCase()) | translate}}</a>
      <a (click)="setCurrentLang()" class="nav-link nav-text">{{currentLang === 'fr' ? 'English' : 'Français'}}</a>
    </div>
  </clr-header>
  <div class="content-container">
    <div style="overflow-y: auto">
      <div id="header-container">
          <div id="header-typewriter-container">
            <h1 class="typewriter"></h1>
          </div>
          <i class="go-down fa fa-angle-down" (click)="scrollToAbout()"></i>
          <video id="videoHomepage" autoplay loop preload muted class="fillWidth" poster="assets/Love-Coding.jpg">
            <source src="assets/Love-Coding.webm" type="video/webm" />
            <source src="assets/Love-Coding.mp4" type="video/mp4" />
            <source src="assets/Love-Coding.ogv" type="video/ogv" />
            <img src="assets/Love-Coding.jpg" title="Your browser does not support the video tag"/>
          </video>
      </div>
      <div class="content-area">
        <ng-content select="[main-content]"></ng-content>
      </div>
      <ng-content select="[footer]"></ng-content>
    </div>
  </div>
</clr-main-container>

// src/components/layout/layout.tsx
import { useTranslation } from "react-i18next";
import { useNavigate } from "react-router-dom";

import styles from "./layout.module.css";
// import classNames from "classnames";
import { SyntheticEvent, useEffect, useRef, useState } from "react";

import logo from "../../assets/header_logo.png";
import { useLinks } from "../../utilities/linkService";
import { SlideOut } from "../slideOut/slideOut";
import { Persona } from "../persona/persona";
import { Education } from "../education/education";
import { Work } from "../work/work";
import { Skills } from "../skills/skills";
import { Volunteering } from "../volunteering/volunteering";
import { Footer } from "../footer/footer";
import { SplashScreen } from "../splashscreen/splashscreen";
import classNames from "classnames";

export function Layout() {
  const { i18n, t } = useTranslation();
  const links = useLinks().sectionLinks;
  const navigate = useNavigate();
  const [slideOpen, setSlideOpen] = useState(false);
  const scrolledRef = useRef(false);

  useEffect(() => {
    const hash = window.location.hash;
    console.log(hash);
    if (hash && !scrolledRef.current) {
      scrolledRef.current = true;
      setTimeout(() => {
        console.log(document.querySelector(hash));
        document.querySelector(hash)?.scrollIntoView({
          behavior: "smooth",
          block: "start",
        });
      }, 100);
    }
  }, []);

  function onLanguageChange() {
    const navigateToLang = i18n.language === "fr" ? "en" : "fr";
    navigate(`/${navigateToLang}`);
    i18n.changeLanguage(navigateToLang);
  }

  function navigateTo(event: SyntheticEvent) {
    const anchorElement = findAnchor(
      event.target as HTMLElement
    ) as HTMLAnchorElement;
    if (anchorElement) {
      navigate(`#${anchorElement.dataset.ref}`);
      document.querySelector(`#${anchorElement.dataset.ref}`)?.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    }

    if (slideOpen) {
      setSlideOpen(false);
    }
  }

  function findAnchor(target: HTMLElement) {
    let t: HTMLElement | null = target;
    while (t && t.tagName !== "A") {
      t = target.parentElement;
    }
    return t;
  }

  return (
    <div className={classNames([styles.mainContainer])}>
      <header className={styles.header}>
        <div className={styles.branding}>
          <button
            className={styles.bars}
            type="button"
            onClick={() => setSlideOpen(true)}
          >
            <i className="fa fa-bars"></i>
          </button>
          <a className={styles.navLink} onClick={navigateTo} data-ref="about">
            <img id={styles.headerLogo} src={logo} />
          </a>
        </div>
        <div className={styles.linkContainer}>
          {links.map((link) => (
            <a
              key={link.display}
              data-ref={link.href}
              onClick={navigateTo}
              className={styles.link}
            >
              {t(`SECTIONS.${link.display.toUpperCase()}`)}
            </a>
          ))}
          <a className={styles.link} onClick={onLanguageChange}>
            {i18n.language === "fr" ? "English" : "Français"}
          </a>
        </div>
      </header>
      <SlideOut open={slideOpen} setSlideOpen={setSlideOpen}>
        <>
          {links.map((link) => (
            <a
              key={link.display}
              data-ref={link.href}
              onClick={navigateTo}
              className={styles.link}
            >
              {t(`SECTIONS.${link.display.toUpperCase()}`)}
            </a>
          ))}
          <a className={styles.link} onClick={onLanguageChange}>
            {i18n.language === "fr" ? "English" : "Français"}
          </a>
        </>
      </SlideOut>
      <div
        id="overlay"
        className={classNames(
          slideOpen && styles.overlay,
          slideOpen && "overlayOpen"
        )}
      ></div>
      <div className={styles.mainContent}>
        <SplashScreen />
        <div style={{ overflowY: "auto", overflowX: "hidden" }}>
          <div className={styles.mainContentContainer}>
            <Persona />
            <Education />
            <Work />
            <Skills />
            <Volunteering />
          </div>
        </div>
        <Footer />
      </div>
    </div>
  );
}
