// src/components/skills/skills.tsx
import { useTranslation } from "react-i18next";
import styles from "./skills.module.css";
import { AnimatedProgress } from "../animated-progress/animated-progress";
import { useState } from "react";

export interface Skill {
  value: number;
  display?: string;
  tooltip?: string;
  key: string;
}

const hardSkillsList: Skill[] = [
  { key: "Java", value: 50 },
  { key: "JavaScript/Node.js", value: 95 },
  { key: ".NET & .NET Core", value: 70 },
  { key: "Angular 2+", value: 80 },
  { key: "ReactJs", value: 95 },
  { key: "Python", value: 85 },
  { key: "Ruby", value: 60 },
  { key: "Ansible", value: 70 },
  { key: "Bash", value: 60 },
  { key: "SQL", value: 60 },
  { key: "Golang", value: 40 },
].sort((a: Skill, b: Skill) => b.value - a.value);

export function Skills() {
  const { t } = useTranslation();
  const [hardSkillsExpanded, setHardSkillsExpanded] = useState(false);

  const hardSkills = hardSkillsExpanded
    ? hardSkillsList
    : hardSkillsList.slice(0, 7);

  function toggleHardSkills() {
    setHardSkillsExpanded((value) => !value);
  }

  return (
    <div className={styles.card}>
      <div id="skills" className="hiddenId"></div>
      <h3>{t("SECTIONS.SKILLS")}</h3>
      <div>
        {hardSkills.map((skill) => (
          <div key={skill.key}>
            <p className={styles.skillHeading}> {skill.key} </p>
            <AnimatedProgress maxValue={skill.value}></AnimatedProgress>
          </div>
        ))}
        <div className={styles.viewMoreContainer}>
          {!hardSkillsExpanded && (
            <span className={styles.viewMore} onClick={toggleHardSkills}>
              {t("VIEW_MORE")}
            </span>
          )}
          {hardSkillsExpanded && (
            <span className={styles.viewMore} onClick={toggleHardSkills}>
              {t("VIEW_LESS")}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

// src/app/skills/skills.component.ts
import { Component, HostListener, ElementRef } from '@angular/core';
import { Skill } from '../../models/skill';

@Component({
  selector: 'app-skills',
  templateUrl: './skills.component.html',
  styleUrls: ['./skills.component.css']
})
export class SkillsComponent {

  public showLoaders = false;

  public softSkills: Skill[] = [
    { key: 'Leadership', currentValue: 0, value: 60 } as Skill,
    { key: 'Work Ethic', currentValue: 0, value: 85 } as Skill,
    { key: 'Positive Attitude', currentValue: 0, value: 80 } as Skill,
    { key: 'Communication', currentValue: 0, value: 90, tooltip: 'English & French', tooltipClass: 'tooltip-sm' } as Skill,
    { key: 'Time Management', currentValue: 0, value: 70 } as Skill,
    { key: 'Problem-Solving Skills', currentValue: 0, value: 80 } as Skill,
    { key: 'Team Player', currentValue: 0, value: 95 } as Skill,
    { key: 'Confidence', currentValue: 0, value: 80 } as Skill,
    { key: 'Learn from Criticism', currentValue: 0, value: 70 } as Skill,
    { key: 'Work under pressure', currentValue: 0, value: 80 } as Skill,
    { key: 'Adaptability', currentValue: 0, value: 85 } as Skill
  ];

  public hardSkills: Skill[] = [
    { key: 'Java', currentValue: 0, value: 50 } as Skill,
    { key: 'Javascript', currentValue: 0, value: 95 } as Skill,
    { key: '.NET & .NET Core', currentValue: 0, value: 80 } as Skill,
    { key: 'AngularJs', currentValue: 0, value: 70 } as Skill,
    { key: 'Angular 2+', currentValue: 0, value: 80 } as Skill,
    { key: 'ReactJs', currentValue: 0, value: 80 } as Skill,
    { key: 'Nodejs + modules', currentValue: 0, value: 90 } as Skill,
    { key: 'Python', currentValue: 0, value: 85 } as Skill,
    { key: 'VueJs', currentValue: 0, value: 15 } as Skill,
    { key: 'Ruby', currentValue: 0, value: 10 } as Skill,
    { key: 'Ansible', currentValue: 0, value: 70 } as Skill,
    { key: 'Capistrano', currentValue: 0, value: 70 } as Skill,
    { key: 'Shell & Bash', currentValue: 0, value: 40 } as Skill,
    { key: 'PHP', currentValue: 0, value: 40 } as Skill,
    { key: 'SQL', currentValue: 0, value: 60 } as Skill
  ];

  public softSkillsExpanded = false;
  public hardSkillsExpanded = false;

  constructor(private el: ElementRef) {
    this.softSkills = this.softSkills.sort((a: Skill, b: Skill) => a.key.localeCompare(b.key));
    this.hardSkills = this.hardSkills.sort((a: Skill, b: Skill) => a.key.localeCompare(b.key));
  }

  public getSoftSkills(): Skill[] {
    return this.softSkillsExpanded ? this.softSkills : this.softSkills.slice(0, 10);
  }

  public getHardSkills(): Skill[] {
    return this.hardSkillsExpanded ? this.hardSkills : this.hardSkills.slice(0, 10);
  }

  public toggleSoftSkillsExpanded(): void {
    this.softSkillsExpanded = !this.softSkillsExpanded;
  }

  public toggleHardSkillsExpanded(): void {
    this.hardSkillsExpanded = !this.hardSkillsExpanded;
  }
}

<div id="skills" class="card">
  <div class="card-block">
    <h3>{{ 'SECTIONS.SKILLS' | translate }}</h3>

    <div class="flex-row">
      <div class="skill-column">
        <h5>{{ 'SKILLS.SOFT' | translate }}</h5>
        <div *ngFor="let skill of getSoftSkills()">
          <p>
            <span>{{ 'SKILLS.' + skill.key.toUpperCase() | translate }}</span>
            <span *ngIf="skill.tooltip" class="tooltip" [ngClass]="skill.tooltipClass ? skill.tooltipClass : 'tooltip-xs'">
              <clr-icon shape="info-circle" size="24"></clr-icon>
              <span class="tooltip-content">{{skill.tooltip}}</span>
            </span>
          </p>
          <div class="progress">
            <progress max="100" value="{{skill.value}}"></progress>
          </div>

        </div>
        <div class="viewMoreContainer">
          <span class="viewMore" *ngIf="!softSkillsExpanded" (click)="toggleSoftSkillsExpanded()">{{ 'VIEW_MORE' | translate }}</span>
          <span class="viewMore" *ngIf="softSkillsExpanded" (click)="toggleSoftSkillsExpanded()">{{ 'VIEW_LESS' | translate }}</span>
        </div>
      </div>
      <div class="skill-column">
        <h5>{{ 'SKILLS.HARD' | translate }}</h5>
        <div *ngFor="let skill of getHardSkills()">
          <p>
            <span>{{skill.key}}</span>
            <span *ngIf="skill.tooltip" class="tooltip" [ngClass]="skill.tooltipClass ? skill.tooltipClass : 'tooltip-xs'">
              <clr-icon shape="info-circle" size="24"></clr-icon>
              <span class="tooltip-content">{{skill.tooltip}}</span>
            </span>
          </p>
          <div class="progress">
            <progress max="100" value="{{skill.value}}"></progress>
          </div>
        </div>
        <div class="viewMoreContainer">
          <span class="viewMore" *ngIf="!hardSkillsExpanded" (click)="toggleHardSkillsExpanded()">{{ 'VIEW_MORE' | translate }}</span>
          <span class="viewMore" *ngIf="hardSkillsExpanded" (click)="toggleHardSkillsExpanded()">{{ 'VIEW_LESS' | translate }}</span>
        </div>
      </div>
    </div>
  </div>
</div>
