// src/components/splashscreen/splashscreen.tsx
import classNames from "classnames";
import styles from "./splashscreen.module.css";
import { useTranslation } from "react-i18next";

import webm from "../../assets/Love-Coding.webm?url";
import ogv from "../../assets/Love-Coding.ogv?url";
import mp4 from "../../assets/Love-Coding.mp4?url";
import poster from "../../assets/Love-Coding.jpg";
import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";

export function SplashScreen() {
  const { t } = useTranslation();
  const [header, setHeader] = useState("");
  const writerRef = useRef<boolean>(false);
  const [delayElementsVisible, setDelayElementsVisible] = useState(false);
  const navigate = useNavigate();
  const videoRef = useRef<HTMLVideoElement>(null);

  function scrollToAbout() {
    navigate("#about");
    document.querySelector("#about")?.scrollIntoView({
      behavior: "smooth",
      block: "start",
    });
  }

  const appearDelay = useCallback(
    (msg: string, delay: number, isFirstLetter = true) => {
      if (msg) {
        setTimeout(
          () => {
            setHeader((header) => (header += msg[0]));
            appearDelay(msg.substring(1), delay, false);
          },
          isFirstLetter ? delay : 25
        );
      }
    },
    []
  );

  useEffect(() => {
    if (!writerRef.current) {
      writerRef.current = true;
      appearDelay("Jonathan Hamel", 2000);

      setTimeout(() => {
        setDelayElementsVisible(true);
      }, 3000);
    }

    if (videoRef.current) {
      // videoRef.current.muted = true;
      // videoRef.current.play();
    }
  }, [appearDelay]);

  return (
    <div id={styles.headerContainer}>
      <div id={styles.headerTypewriterContainer}>
        <h1 className={styles.appearDelay}>{header}</h1>
        <h1 className={classNames([styles.initialBlinking, styles.lightgray])}>
          |
        </h1>
        <h3
          className={classNames([
            styles.fadeInLate,
            styles.titleLabel,
            delayElementsVisible && styles.ready,
          ])}
        >
          {t("TITLE")}
        </h3>
      </div>
      <div className={styles.arrowContainer}>
        <i
          className={classNames([
            styles.goDown,
            "fa fa-angle-down",
            styles.fadeInLate,
            delayElementsVisible && styles.ready,
          ])}
          onClick={scrollToAbout}
        ></i>
      </div>
      <video
        autoPlay
        id={styles.videoHomepage}
        loop
        muted
        ref={videoRef}
        className={styles.fillWidth}
        poster={poster}
      >
        <source src={webm} type="video/webm" />
        <source src={mp4} type="video/mp4" />
        <source src={ogv} type="video/ogv" />
        <img
          src="assets/Love-Coding.jpg"
          title="Your browser does not support the video tag"
        />
      </video>
    </div>
  );
}

// src/app/splashscreen/splashscreen.component.ts
import { Component, AfterViewInit, OnInit, ViewChild, ElementRef } from '@angular/core';
import { Utils } from '../../services/Utils';

@Component({
  selector: 'app-splashscreen',
  templateUrl: './splashscreen.component.html',
  styleUrls: ['./splashscreen.component.css']
})
export class SplashscreenComponent implements OnInit, AfterViewInit {

  @ViewChild('videoHomepage', { static: true }) videoHomepage!: ElementRef<HTMLVideoElement>;

  public header: string = "";
  public delayTitle: string = "";
  public delayArrow: string = "";

  constructor() { }

  public ngOnInit() {
    this.appearDelay("Jonathan Hamel", 2000, "header");
    Utils.setValueDelay("ready", ["delayTitle", "delayArrow"], this, 3000);
  }

  public ngAfterViewInit() {
    const videoTag = this.videoHomepage.nativeElement;
    videoTag.muted = true;
    videoTag.play();
  }

  public scrollToAbout() {
    document.querySelector('#about').scrollIntoView({
      behavior: 'smooth',
      block: 'start'
    });
  }

  private appearDelay(msg: string, delay: number, varReference: string, isFirstLetter = true) {
    if (isFirstLetter) {
      this[varReference] = "";
    }

    if (msg) {
      const timeout = setTimeout(() => {
        this[varReference] += msg[0];
        this.appearDelay(msg.substring(1), delay, varReference, false);
        clearTimeout(timeout);
      }, (isFirstLetter ? delay : 25));
    }
  }
}

<div id="header-container">
  <div id="header-typewriter-container">
    <h1 class="appear-delay">{{header}}</h1>
    <h1 class="initial-blinking lightgray">|</h1>
    <h3 [ngClass]="['fade-in-late title-label', delayTitle]">{{'TITLE' | translate}}</h3>
  </div>
  <div class="arrow-container">
    <i [ngClass]="['go-down fa fa-angle-down fade-in-late', delayArrow]" (click)="scrollToAbout()"></i>
  </div>
  <video id="videoHomepage" #videoHomepage autoplay loop preload muted="muted" class="fillWidth"
    poster="assets/Love-Coding.jpg">
    <source src="assets/Love-Coding.webm" type="video/webm" />
    <source src="assets/Love-Coding.mp4" type="video/mp4" />
    <source src="assets/Love-Coding.ogv" type="video/ogv" />
    <img src="assets/Love-Coding.jpg" title="Your browser does not support the video tag" />
  </video>
</div>
