// src/app/work/work.component.ts
import { Component } from "@angular/core";
import { TranslateService } from "@ngx-translate/core";

@Component({
  selector: "app-work",
  templateUrl: "./work.component.html",
  styleUrls: ["./work.component.css"],
})
export class WorkComponent {
  constructor(private translate: TranslateService) {
    translate.setDefaultLang("en");
  }

  public getWork() {
    const work = this.translate.instant("WORK");
    return Array.isArray(work) ? work : [];
  }

  public getWorkClass(i: number) {
    const { previousSame, nextSame } = this.getJobPosition(i);

    if (previousSame && nextSame) {
      return "dot-up dot-down";
    }

    if (previousSame) {
      return "dot-up";
    }

    if (nextSame) {
      return "dot-down";
    }
  }

  public shouldShowCompany(i: number) {
    const { previousSame } = this.getJobPosition(i);
    return !previousSame;
  }

  private getJobPosition(i: number) {
    const work = this.getWork();
    const previousSame = work[i - 1] && work[i - 1].COMPANY === work[i].COMPANY;
    const nextSame = work[i + 1] && work[i + 1].COMPANY === work[i].COMPANY;

    return { previousSame, previous: work[i - 1], work, nextSame, next: work[i + 1] };
  }
}

<div id="work" class="card">
  <div class="card-block">
    <h3 class="anchor-offset">{{ "SECTIONS.WORK" | translate }}</h3>
    <div class="flex-row" *ngFor="let work of getWork(); let i = index">
      <div style="position: relative" class="{{ getWorkClass(i) }}">
        <div class="dot"></div>
      </div>
      <div class="work-company">
        <p *ngIf="shouldShowCompany(i); else emptyCompany" style="font-weight: bold">{{ work.COMPANY }}</p>
        <p class="remove-spacing reduce-font">{{ work.DATE }}</p>
      </div>
      <div>
        <p style="font-weight: bold">{{ work.POSITION }}</p>
        <p class="remove-spacing reduce-font">{{ work.DESCRIPTION }}</p>
      </div>
    </div>
  </div>
</div>

<ng-template #emptyCompany>
  <p></p>
</ng-template>

// src/components/work/work.tsx
import { useTranslation } from "react-i18next";
import styles from "./work.module.css";
import classNames from "classnames";

export function Work() {
  const { t } = useTranslation();
  const work = t("WORK", { returnObjects: true }) as {
    COMPANY: string;
    POSITION: string;
    DATE: string;
    DESCRIPTION: string;
  }[];

  function getWorkClass(i: number) {
    const { previousSame, nextSame } = getJobPosition(i);

    if (previousSame && nextSame) {
      return classNames([styles.dotUp, styles.dotDown]);
    }

    if (previousSame) {
      return styles.dotUp;
    }

    if (nextSame) {
      return styles.dotDown;
    }
  }

  function shouldShowCompany(i: number) {
    const { previousSame } = getJobPosition(i);
    return !previousSame;
  }

  function getJobPosition(i: number) {
    const previousSame = work[i - 1] && work[i - 1].COMPANY === work[i].COMPANY;
    const nextSame = work[i + 1] && work[i + 1].COMPANY === work[i].COMPANY;

    return {
      previousSame,
      previous: work[i - 1],
      work,
      nextSame,
      next: work[i + 1],
    };
  }

  return (
    <div className={styles.card}>
      <div id="work" className="hiddenId"></div>
      <h3 className="anchor-offset">{t("SECTIONS.WORK")}</h3>
      {work.map((work, i) => (
        <div key={work.COMPANY + i} className={styles.flexRow}>
          <div style={{ position: "relative" }} className={getWorkClass(i)}>
            <div className={styles.dot}></div>
          </div>
          <div className={styles.workCompany}>
            {shouldShowCompany(i) && (
              <p
                className={styles.removeSpacing}
                style={{ fontWeight: "bold" }}
              >
                {work.COMPANY}
              </p>
            )}
            <p className={styles.reduceFont}>{work.DATE}</p>
          </div>
          <div>
            <p className={styles.workPosition}>{work.POSITION}</p>
            <p className={styles.reduceFont}>{work.DESCRIPTION}</p>
          </div>
        </div>
      ))}
    </div>
  );
}
